# Generated by Django 4.0.5 on 2022-07-04 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_books_category_alter_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='book_image'),
        ),
    ]
