# Generated by Django 4.0.5 on 2022-07-06 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_alter_books_category_alter_books_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='Book.orders'),
        ),
    ]
