# Generated by Django 4.0.6 on 2022-07-06 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_profile_email_profile_name_profile_password'),
        ('Book', '0005_alter_books_category_alter_books_user'),
    ]

    operations = [
    ]
