# Generated by Django 4.0.6 on 2022-07-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_payment_amount_no_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
