# Generated by Django 4.0.5 on 2022-07-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_alter_payment_amount_no_alter_payment_order'),
        ('Book', '0007_alter_cart_options_cart_cart_id_cart_created_at'),
    ]

    operations = [
    ]
