# Generated by Django 4.0.5 on 2022-07-09 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_book_customer_alter_cart_options_cart_cart_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='year_published',
        ),
    ]
