# Generated by Django 4.0.6 on 2022-07-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_remove_burgain_book_burgain_books_delete_book'),
        ('Book', '0009_remove_book_year_published'),
    ]

    operations = [
    ]
